version: '3'

services:
  app:
    build: .
    image: mcodegeeks/homepage
    container_name: homepage
    restart: unless-stopped
    command: gunicorn -b unix:/data-volume/nginx/gunicorn.sock -b :5000 wsgi:app
    volumes:
      - data-volume:/data-volume
    ports:
      - "5000:5000"

  web:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - data-volume:/data-volume
    ports:
      - "80:80"

volumes:
  data-volume: 
    external: true
