version: '3'

services:
  app:
    build: .
    image: mcodegeeks/homepage
    container_name: homepage
    restart: unless-stopped
    command: gunicorn -b unix:/data/nginx/gunicorn.sock -b :5000 wsgi:app
    volumes:
      - volume-homepage:/data/app
      - volume-nginx:/data/nginx
      - volume-postgres:/data/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  web:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - volume-nginx:/data/nginx
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres
    restart: unless-stopped    
    container_name: postgres
    volumes:
      - volume-postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  volume-homepage: 
    external: true  
  volume-nginx: 
    external: true
  volume-postgres: 
    external: true