version: '3'

services:
  app:
    build: .
    image: mcodegeeks/homepage
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - ./app:/user/src/app
    ports:
      - 5000:5000
    container_name: homepage
